openapi: 3.0.3
info:
  title: Kotlin Server on Ktor
  version: 1.0.0
  contact:
    name: Mikhail Salnikov
    email: salnikovmishanew@gmail.com

servers:
  - url: https://localhost:8085/api/v1
    description: Rest Api Server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      required:
        - token
      properties:
        token:
          type: string
    LoginNotAuth:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    ProtectedCheck:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    Users:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
    UsersForAdmin:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        password:
          type: string

paths:
  /login:
    get:
      summary: Авторизация
      description: При корректной авторизации, пользователь получает токен
      tags:
        - Login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "200":
          description: "Токен"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "401":
          description: "Ошибка авторизации"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginNotAuth"

  /protectedCheck:
    get:
      summary: Проверка токена
      description: Проверка токена на валидность
      tags:
        - Login
      security:
        - bearerAuth: []
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProtectedCheck"

  /users:
    get:
      summary: Пользователи
      description: Получение списка пользователей
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Users"

tags:
  - name: Login
    description: "Авторизация"
  - name: Users
    description: "Пользователи"
externalDocs:
  description: Find more info here
  url: https://github.com/mrRazmarin/kotlin-ktor-example
